# Generated by Django 5.2.1 on 2025-06-05 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participants', models.ManyToManyField(to='api.participant')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.receipt')),
            ],
            options={
                'db_table': 'settlement',
            },
        ),
    ]
