# Generated by Django 5.2.1 on 2025-06-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='method',
            field=models.CharField(choices=[('equal', 'Equal Split (N분의1)'), ('item', 'Item Split (항목별)')], default='equal', max_length=10),
        ),
    ]
