# Generated by Django 5.2.1 on 2025-06-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_settlement_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='receipt',
        ),
        migrations.AddField(
            model_name='settlement',
            name='receipts',
            field=models.ManyToManyField(to='api.receipt'),
        ),
    ]
