# Generated by Django 5.2.1 on 2025-05-27 14:10


import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[

                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_path', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
    ]
