# Generated by Django 5.2.1 on 2025-05-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.receipt')),
            ],
            options={
                'db_table': 'receipt_info',
            },
        ),
    ]
