# Generated by Django 5.2.1 on 2025-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_settlement_receipt_settlement_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='item_assignments_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
